---
apiVersion: v1
kind: Service
metadata:
  name: metastore
spec:
  ports:
  - port: 9083
    targetPort: 9083
  selector:
    app: metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore
spec:
  selector:
    matchLabels:
      app: metastore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metastore
    spec:
      containers:
      - name: metastore
        #image: docker.io/joshuarobinson/hivemetastore
        image: docker.io/janiomanio/metastore:0.7
        #image: docker.io/timveil/docker-hadoop-hive-metastore-standalone
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: secretkey
        - name: METASTORE_HOME
          value: /opt/hive-metastore
        ports:
        - containerPort: 9083
#        livenessProbe:
#          tcpSocket:
#            port: 9083
#        readinessProbe:
#          tcpSocket:
#            port: 9083
        volumeMounts:
        - name: metastore-cfg-vol
          mountPath: /opt/hive-metastore/conf/metastore-site.xml
          subPath: metastore-site.xml
        - name: metastore-cfg-vol
          mountPath: /opt/hadoop/etc/hadoop/core-site.xml
          subPath: core-site.xml
        command: ["/opt/hive-metastore/bin/start-metastore"]
        args: ["-p", "9083"]
        resources:
          requests:
            memory: "1G"
        imagePullPolicy: Always
      volumes:
        - name: metastore-cfg-vol
          configMap:
            name: metastore-cfg
